name = "CStarSurfaces"
uuid = "42ef8a1c-faf6-41db-96e1-562c4470a736"
authors = ["Justus Springer <justusspringer@gmx.de>"]
version = "0.1.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CustomUnitRanges = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
Combinatorics = "1.0.2"
CustomUnitRanges = "1.0.2"
Oscar = "0.13.0"
julia = "1.6"
